@BASE_URL = http://localhost:5251
@BOOK_RED_RISING_ID = EE8C61BF-BABF-46D1-9A63-C640CDF9B52D

GET {{BASE_URL}}/books/
Accept: application/json

###
GET {{BASE_URL}}/books/{{BOOK_RED_RISING_ID}}

###
POST {{BASE_URL}}/books
Accept: application/json
Content-Type: application/json

{
    "title": "Dopamine Nation: Finding Balance in the Age of Indulgence",
    "author": "Anna Lembke",
    "price": 18.42
}

###
DELETE {{BASE_URL}}/books/7083A0F1-57D0-465B-9B3A-FD942BAD5D55
Accept: application/json

###
PATCH {{BASE_URL}}/books/{{BOOK_RED_RISING_ID}}/price
Accept: application/json
Content-Type: application/json

{
    "price": 10.42
}